/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'outline-variant': '#c3c6d0',
        'on-secondary-fixed': '#001e2c',
        'surface-container-low': '#f3f4f5',
        'surface-container-highest': '#e1e3e4',
        'on-secondary': '#ffffff',
        'surface-bright': '#f8f9fa',
        'surface-container-high': '#e7e8e9',
        'on-secondary-fixed-variant': '#004c69',
        'tertiary-fixed-dim': '#ffba30',
        'primary-fixed-dim': '#a6c8ff',
        'inverse-surface': '#2e3132',
        surface: '#f8f9fa',
        'surface-tint': '#3b5f92',
        'on-surface-variant': '#43474f',
        'on-primary-fixed': '#001c3b',
        'tertiary-fixed': '#ffdeab',
        'secondary-fixed': '#c4e7ff',
        'surface-dim': '#d9dadb',
        primary: '#001d3d',
        'inverse-primary': '#a6c8ff',
        'surface-container-lowest': '#ffffff',
        'on-primary': '#ffffff',
        'on-surface': '#191c1d',
        background: '#f8f9fa',
        'on-secondary-container': '#0d5e80',
        'secondary-fixed-dim': '#8fcef5',
        'secondary-container': '#97d7fd',
        secondary: '#1a6587',
        outline: '#737780',
        'on-primary-fixed-variant': '#204778',
        'surface-variant': '#e1e3e4',
        'tertiary-container': '#442e00',
        tertiary: '#291a00',
        'on-tertiary': '#ffffff',
        'primary-container': '#003262',
        'on-primary-container': '#789bd2',
        'on-background': '#191c1d',
        'on-tertiary-container': '#cb8f00',
        'surface-container': '#edeeef',
        'primary-fixed': '#d5e3ff',
        error: '#ba1a1a',
      },
      fontFamily: {
        headline: ['Newsreader', 'serif'],
        body: ['Inter', 'sans-serif'],
        label: ['Inter', 'sans-serif'],
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
    },
  },
  plugins: [],
};
